# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(930, 662)
        Home.setStyleSheet("QWidget {\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"}\n"
"\n"
"#withdraw_button,\n"
"#donate_button,\n"
"#balance_button {\n"
"    background-color: #DAE8FC;\n"
"    text-align: left;\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"#logout_button {\n"
"    background-color: #F8CECC;\n"
"    text-align: right;\n"
"    padding-right: 16px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Home)
        self.verticalLayout.setContentsMargins(0, 16, 0, 16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Home)
        self.label.setMinimumSize(QtCore.QSize(0, 200))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.withdraw_button = QtWidgets.QPushButton(Home)
        self.withdraw_button.setMinimumSize(QtCore.QSize(175, 50))
        self.withdraw_button.setObjectName("withdraw_button")
        self.verticalLayout_2.addWidget(self.withdraw_button)
        self.donate_button = QtWidgets.QPushButton(Home)
        self.donate_button.setMinimumSize(QtCore.QSize(175, 50))
        self.donate_button.setObjectName("donate_button")
        self.verticalLayout_2.addWidget(self.donate_button)
        self.balance_button = QtWidgets.QPushButton(Home)
        self.balance_button.setMinimumSize(QtCore.QSize(175, 50))
        self.balance_button.setObjectName("balance_button")
        self.verticalLayout_2.addWidget(self.balance_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.logout_button = QtWidgets.QPushButton(Home)
        self.logout_button.setMinimumSize(QtCore.QSize(175, 50))
        self.logout_button.setObjectName("logout_button")
        self.verticalLayout_3.addWidget(self.logout_button)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Form"))
        self.label.setText(_translate("Home", "Herbank"))
        self.withdraw_button.setText(_translate("Home", "Geld opnemen"))
        self.donate_button.setText(_translate("Home", "Geld doneren"))
        self.balance_button.setText(_translate("Home", "Saldo raadplegen"))
        self.logout_button.setText(_translate("Home", "Uitloggen"))
